from django.utils.translation import gettext_lazy as _

ALLOWED_TAGS = [
    ("personnel santé", _("personnel santé")),
    ("alimentaire", _("alimentaire")),
    ("éducation", _("éducation")),
    ("télétravail", _("télétravail")),
    ("sécurité", _("sécurité")),
    ("transport", _("transport")),
    ("étudiant", _("étudiant")),
    ("sport", _("sport")),
    ("voyage", _("voyage")),
    ("art & culture", _("art & culture")),
    ("cuisine", _("cuisine")),
    ("nature & environnement", _("nature & environnement")),
    ("famille", _("famille")),
    ("amitié", _("amitié")),
    ("amour", _("amour")),
    ("solitude", _("solitude")),
    ("confinement", _("confinement")),
    ("positivité", _("positivité")),
    ("motivation", _("motivation")),
    ("humour", _("humour")),
    ("actualités", _("actualités")),
    ("covid+", _("covid+")),
]
